version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:80
        volumes:
            - .:/var/www/html
        depends_on:
            - db
    db:
        image: postgres
        environment:
            POSTGRES_DB: eventRegistrationSystem
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 18811938tr
        ports:
            - 5432:5432
